const ITEMS = [
  {
    type: "image",
    src: "media/IMG_0128.jpg",
    caption: "Test caption — one liner",
  },
  {
    type: "image",
    src: "media/IMG_0859.JPG",
    caption: "Second test\nWith a second line",
  },
  { type: "image", src: "media/IMG_3315.JPG", caption: "Third test caption" },
  { type: "image", src: "media/IMG_5364.PNG", caption: "" },
  { type: "image", src: "media/IMG_5423.jpg", caption: "" },
  { type: "image", src: "media/IMG_5424.jpg", caption: "" },
  { type: "image", src: "media/IMG_5429.JPG", caption: "" },
  { type: "image", src: "media/IMG_5430.jpg", caption: "" },
  { type: "image", src: "media/IMG_5433.jpg", caption: "" },
  { type: "image", src: "media/IMG_5434.PNG", caption: "" },
  { type: "image", src: "media/IMG_5787.JPG", caption: "" },
  { type: "image", src: "media/IMG_5814.JPG", caption: "" },
  { type: "video", src: "media/RPReplay_Final1644376321.mov", caption: "" },
  { type: "image", src: "media/IMG_6058.jpg", caption: "" },
  { type: "image", src: "media/IMG_6096.jpg", caption: "" },
  { type: "image", src: "media/IMG_6107.jpg", caption: "" },
  { type: "image", src: "media/IMG_6119.jpg", caption: "" },
  { type: "image", src: "media/IMG_6382.jpg", caption: "" },
  { type: "image", src: "media/IMG_6591.jpg", caption: "" },
  { type: "image", src: "media/IMG_6740.jpg", caption: "" },
  { type: "image", src: "media/IMG_6900.jpg", caption: "" },
  { type: "image", src: "media/IMG_7587.jpg", caption: "" },
  { type: "image", src: "media/IMG_8119.jpg", caption: "" },
  { type: "video", src: "media/RPReplay_Final1659630609.mov", caption: "" },
  { type: "image", src: "media/IMG_8139.jpg", caption: "" },
  { type: "image", src: "media/IMG_8211.jpg", caption: "" },
  { type: "image", src: "media/IMG_8371.jpg", caption: "" },
  { type: "image", src: "media/IMG_8508.jpg", caption: "" },
  { type: "image", src: "media/IMG_8723.jpg", caption: "" },
  { type: "image", src: "media/IMG_8735.jpg", caption: "" },
  { type: "image", src: "media/IMG_8755.jpg", caption: "" },
  { type: "video", src: "media/RPReplay_Final1668641161.mov", caption: "" },
  { type: "image", src: "media/IMG_9143.WEBP", caption: "" },
  { type: "image", src: "media/IMG_9188.jpg", caption: "" },
  { type: "image", src: "media/IMG_9292.jpg", caption: "" },
  { type: "image", src: "media/IMG_9350.WEBP", caption: "" },
  { type: "image", src: "media/IMG_9390.JPG", caption: "" },
  { type: "image", src: "media/IMG_9410.JPG", caption: "" },
  { type: "image", src: "media/IMG_9717.jpg", caption: "" },
  { type: "image", src: "media/IMG_9762.JPG", caption: "" },
  { type: "image", src: "media/IMG_9819.jpg", caption: "" },
];
