const ITEMS = [
  { type: "image", src: "media/IMG_5423.jpg", caption: "2016, the golden age" },
  {
    type: "image",
    src: "media/IMG_5429.JPG",
    caption: "e/acc",
  },
  { type: "image", src: "media/IMG_5430.jpg", caption: "final fantasy" },
  {
    type: "video",
    src: "media/RPReplay_Final1644376321.mov",
    caption: "famous",
  },
  {
    type: "image",
    src: "media/IMG_6058.jpg",
    caption: "beauty through engineering",
  },
  { type: "image", src: "media/IMG_6096.jpg", caption: "school picture" },
  { type: "image", src: "media/IMG_6382.jpg", caption: "famous v2" },
  { type: "image", src: "media/IMG_6900.jpg", caption: "halo" },
  {
    type: "image",
    src: "media/IMG_7587.jpg",
    caption: "beauty through engineering v2",
  },
  {
    type: "video",
    src: "media/RPReplay_Final1659630609.mov",
    caption: "top gun",
  },
  { type: "image", src: "media/IMG_8723.jpg", caption: "VMAs" },
  {
    type: "image",
    src: "media/IMG_8735.jpg",
    caption: "the split, life & work",
  },
  { type: "image", src: "media/IMG_8755.jpg", caption: "dragon jerseys" },
  {
    type: "video",
    src: "media/RPReplay_Final1668641161.mov",
    caption: "let go, revenge of the sith",
  },
  {
    type: "image",
    src: "media/IMG_9188.jpg",
    caption: "the sacrifice of horses",
  },
  { type: "image", src: "media/IMG_9292.jpg", caption: "four nations ad" },
  {
    type: "image",
    src: "media/IMG_9350.WEBP",
    caption: "goated star wars poster",
  },
  {
    type: "image",
    src: "media/IMG_9390.JPG",
    caption:
      "you do not realize now what I am doing, but later you will understand",
  },
  {
    type: "image",
    src: "media/IMG_9717.jpg",
    caption:
      '"I don\'t know if things are ever going back to the way they were" -suits',
  },
  { type: "image", src: "media/IMG_5424.jpg", caption: "PROMISE KEEPER" },
  { type: "image", src: "media/IMG_9819.jpg", caption: "100% Jesus" },
  { type: "image", src: "media/4uU6eHXGeNUz6vwkS47ch5.jpg", caption: "dex" },
  { type: "image", src: "media/552.gif", caption: "cannae :(" },
  { type: "video", src: "media/CGj85pVzRJs.mp4", caption: "let it be" },
  {
    type: "image",
    src: "media/81773498007-91-91685.webp",
    caption: "gsp",
  },
  { type: "image", src: "media/Casablanca.webp", caption: "Casablanca" },
  {
    type: "video",
    src: "media/lN8kTFPhQTo.mp4",
    caption: "underground tournament",
  },
  {
    type: "image",
    src: "media/CrosbyGoldenGoal.jpg",
    caption: "Golden Goal",
  },
  {
    type: "image",
    src: "media/Cx4V5vwXAAASUVa.jpg",
    caption: "mbdtf studio rules",
  },
  { type: "video", src: "media/u-pP_dCenJA.mp4", caption: "if i can dream" },
  {
    type: "image",
    src: "media/Elvis_Presley_in_Germany.jpg",
    caption: "elvis in germany",
  },
  { type: "image", src: "media/Firm_ver2.jpg", caption: "peak tom cruise" },
  {
    type: "image",
    src: "media/To_Catch_a_Thief.jpg",
    caption: "to catch a thief",
  },
  {
    type: "video",
    src: "media/IJrjcHx9nDA.mp4",
    caption: "women in a red dress",
  },
  {
    type: "video",
    src: "media/orVonJwofD8.mp4",
    caption: "american excellence",
  },
  {
    type: "image",
    src: "media/Fv797Y9XoAMrVFO.png",
    caption: "michael burry, black swan",
  },
  {
    type: "image",
    src: "media/G0Lt1saXMAAMIW9.jpeg",
    caption: "henry ford quote",
  },
  {
    type: "video",
    src: "media/XthuZf-7A-s.mp4",
    caption: "the social network",
  },
  {
    type: "image",
    src: "media/GBrNNgtWcAEt43g.jpg",
    caption: "big city, bigger dreams",
  },
  {
    type: "image",
    src: "media/Goldfinger-James-Bond.jpg",
    caption: "goldfinger, golf scene",
  },
  { type: "video", src: "media/O_X6BWJvGfo.mp4", caption: "tiger" },
  {
    type: "image",
    src: "media/GzD5B4nWUAA4sba.jpeg",
    caption: "nietzsche",
  },
  {
    type: "image",
    src: "media/Lionel_Royer_-_Vercingetorix_Throwing_down_His_Weapons_at_the_feet_of_Julius_Caesar.jpg",
    caption: "Vercingetorix vs Caeser, Gaul is lost",
  },
  {
    type: "image",
    src: "media/RSMarch15.avif",
    caption: "ides of march",
  },
  {
    type: "video",
    src: "media/vU26Pa6ERkY.mp4",
    caption: "geohot, comma days",
  },
  {
    type: "image",
    src: "media/VF1022_Hitchcock_Architecture_1.webp",
    caption: "north by northwest",
  },
  {
    type: "image",
    src: "media/az8g0uuockg31.jpg",
    caption: "2016 real madrid, best kits",
  },
  { type: "video", src: "media/GEPhLqwKo6g.mp4", caption: "think different" },
  {
    type: "image",
    src: "media/d1a43a2eaea762f81cbdc49dcc35e55d.428x521x1.png",
    caption: "tlop, track list",
  },
  { type: "image", src: "media/hq720.jpg", caption: '"are you okay?"' },
  { type: "image", src: "media/images.jpeg", caption: "naruto" },
  { type: "video", src: "media/ErwS24cBZPc.mp4", caption: "1984" },
  {
    type: "image",
    src: "media/limitless.webp",
    caption: "a pill a day and what I could do with my day was limitless",
  },
  { type: "image", src: "media/photo.avif", caption: "spacex, early launches" },
  {
    type: "video",
    src: "media/Gvf547kGOXs.mp4",
    caption: "founder fund, opening credits",
  },
  {
    type: "image",
    src: "media/pretty-woman.webp",
    caption: "pretty woman",
  },
  {
    type: "image",
    src: "media/steve-jobs-ibm-finger.jpg",
    caption: "steve @ ibm",
  },
  {
    type: "image",
    src: "media/the-living-daylights-is-one-of-my-favourite-007-movies-this-v0-hav3nip2ifqe1.webp",
    caption: "the living daylights",
  },
  { type: "video", src: "media/XF3nEmKziWU.mp4", caption: "LKY, Singapore" },
  {
    type: "image",
    src: "media/the-manga-art-is-legendary-but-can-we-also-appreciate-the-v0-afvuryjeal6b1.jpg",
    caption: "berzerk 1997",
  },
  {
    type: "image",
    src: "media/why-did-michael-rob-a-bank-if-he-didnt-need-the-money-why-v0-wlzfllhe5doe1.webp",
    caption: "scofield",
  },
  { type: "video", src: "media/L2e8sbpyj_g.mp4", caption: "ripple" },
];
