// Search Index for Portfolio Website
// This file contains all searchable content across the site

const SEARCH_INDEX = [
  // Main Pages
  {
    id: "page-home",
    title: "Home",
    type: "page",
    category: "Navigation",
    description: "Main landing page with bio and current activities",
    tags: [
      "home",
      "about",
      "bio",
      "ethan",
      "cratchley",
      "computer science",
      "business",
    ],
    url: "/",
    breadcrumb: "Home",
  },
  {
    id: "page-writing",
    title: "Writing",
    type: "page",
    category: "Navigation",
    description: "Technical articles, essays, and reflections",
    tags: ["writing", "blog", "articles", "essays", "technical"],
    url: "/writing/",
    breadcrumb: "Writing",
  },
  {
    id: "page-experience",
    title: "Experience",
    type: "page",
    category: "Navigation",
    description: "Work experience, education, and volunteer activities",
    tags: ["experience", "work", "education", "resume", "cv"],
    url: "/experience/",
    breadcrumb: "Experience",
  },
  {
    id: "page-projects",
    title: "Projects",
    type: "page",
    category: "Navigation",
    description: "Software projects and technical work",
    tags: ["projects", "portfolio", "code", "github"],
    url: "/projects/",
    breadcrumb: "Projects",
  },
  {
    id: "page-garden",
    title: "Garden",
    type: "page",
    category: "Navigation",
    description:
      "Ideas, resources, and fleeting thoughts - curated websites, videos, books, papers, and personal notes",
    tags: [
      "garden",
      "resources",
      "thoughts",
      "ideas",
      "books",
      "papers",
      "videos",
      "notes",
      "learning",
      "collection",
    ],
    url: "/garden/",
    breadcrumb: "Garden",
  },
  {
    id: "page-contact",
    title: "Contact",
    type: "page",
    category: "Navigation",
    description: "Get in touch and connect on social platforms",
    tags: ["contact", "email", "linkedin", "github", "social"],
    url: "/contact/",
    breadcrumb: "Contact",
  },

  // Projects - Featured
  {
    id: "project-solaris",
    title: "Solar Energy Optimizer",
    type: "project",
    category: "Electronics",
    description:
      "Arduino based system that orients solar panels with servos and sensors for optimal energy",
    tags: [
      "electronics",
      "arduino",
      "solar",
      "renewable energy",
      "hardware",
      "sensors",
    ],
    url: "https://github.com/EthanCratchley/solaris",
    breadcrumb: "Projects > Electronics",
  },
  {
    id: "project-custorix",
    title: "Custorix",
    type: "project",
    category: "AI, Cybersecurity",
    description:
      "Private, offline first, multimodal AI security system using Gemma 3n",
    tags: [
      "ai",
      "cybersecurity",
      "electronics",
      "security",
      "gemma",
      "multimodal",
      "privacy",
    ],
    url: "https://github.com/EthanCratchley/custorix",
    breadcrumb: "Projects > AI, Cybersecurity",
  },
  {
    id: "project-rag",
    title: "Fine Tuning & RAG Development",
    type: "project",
    category: "AI",
    description:
      "Developing Retrieval-Augmented Generation (RAG) models and fine-tuning LLMs",
    tags: ["ai", "llm", "rag", "fine-tuning", "machine learning", "autonommi"],
    url: "https://autonommi.com/",
    breadcrumb: "Projects > AI",
  },
  {
    id: "project-kaggle",
    title: "Kaggle and CTF Competitions",
    type: "project",
    category: "AI, Cybersecurity",
    description:
      "Kaggle and CTF Competitions using various ML, DL, and Cyber Security techniques",
    tags: [
      "ai",
      "cybersecurity",
      "kaggle",
      "ctf",
      "competitions",
      "machine learning",
      "security",
    ],
    url: "https://www.kaggle.com/ethancratchley",
    breadcrumb: "Projects > AI, Cybersecurity",
  },
  {
    id: "project-fff",
    title: "Financial Fast Feed",
    type: "project",
    category: "AI",
    description:
      "Summarizes and displays financial news from RSS feeds using OpenAI API",
    tags: ["ai", "finance", "news", "openai", "rss", "summarization"],
    url: "https://www.financialfastfeed.com/",
    breadcrumb: "Projects > AI",
  },
  {
    id: "project-phishsleuth",
    title: "PhishSleuth",
    type: "project",
    category: "AI, Cybersecurity",
    description:
      "Lightweight Static Analysis and AI for Phishing and Attachment Detection in Email",
    tags: ["ai", "cybersecurity", "phishing", "email", "security", "detection"],
    url: "https://github.com/EthanCratchley/PhishSleuth",
    breadcrumb: "Projects > AI, Cybersecurity",
  },

  // Projects - Archive
  {
    id: "project-finance-models",
    title: "Financial Modelling",
    type: "project",
    category: "Finance",
    description: "Financial modeling and analysis tools",
    tags: ["finance", "modeling", "analysis", "dcf", "valuation"],
    url: "https://github.com/EthanCratchley/finance_models",
    breadcrumb: "Projects > Archive > Finance",
  },
  {
    id: "project-embr",
    title: "Embr Fires",
    type: "project",
    category: "AI, Hackathon",
    description: "Wildfire prediction and monitoring system",
    tags: ["ai", "hackathon", "fires", "prediction", "nwhacks"],
    url: "https://github.com/minhVu03/nwHacks2025",
    breadcrumb: "Projects > Archive > Hackathon",
  },
  {
    id: "project-sfic",
    title: "SFIC Database",
    type: "project",
    category: "Web Development",
    description: "Database system for Simon Fraser Investment Club",
    tags: ["web", "database", "investment", "club"],
    url: "https://sfic.ca/",
    breadcrumb: "Projects > Archive > Web",
  },
  {
    id: "project-algo-trading",
    title: "Algo Trading",
    type: "project",
    category: "Finance, AI",
    description: "Algorithmic trading strategies and backtesting",
    tags: ["finance", "trading", "algorithms", "backtesting", "quantitative"],
    url: "https://github.com/EthanCratchley/algo-trading",
    breadcrumb: "Projects > Archive > Finance",
  },
  {
    id: "project-l2l",
    title: "Launch to Learn",
    type: "project",
    category: "Education, Hackathon",
    description: "Educational platform for learning",
    tags: ["education", "learning", "hackathon", "web"],
    url: "https://github.com/EthanCratchley/learn2launch",
    breadcrumb: "Projects > Archive > Hackathon",
  },
  {
    id: "project-winter-watch",
    title: "Winter Watch",
    type: "project",
    category: "Web Development, Hackathon",
    description: "Winter weather monitoring and alerts",
    tags: ["weather", "monitoring", "hackathon", "web"],
    url: "https://github.com/EthanCratchley/winter-watch",
    breadcrumb: "Projects > Archive > Hackathon",
  },

  // Writing - Technical
  {
    id: "writing-instafeed",
    title: "Instagram Feed System Design",
    type: "writing",
    category: "Technical",
    description: "System design analysis of Instagram's feed architecture",
    tags: [
      "technical",
      "system design",
      "instagram",
      "architecture",
      "distributed systems",
    ],
    url: "/writing/microblogFiles/instafeed.html",
    breadcrumb: "Writing > Technical",
  },
  {
    id: "writing-kaggle",
    title: "Meta Kaggle Hackathon",
    type: "writing",
    category: "Technical",
    description: "Experience and learnings from Meta Kaggle competition",
    tags: [
      "technical",
      "kaggle",
      "hackathon",
      "meta",
      "machine learning",
      "competition",
    ],
    url: "/writing/microblogFiles/kaggle.html",
    breadcrumb: "Writing > Technical",
  },
  {
    id: "writing-llm-quality",
    title: "Forgetful Middles in LLMs",
    type: "writing",
    category: "Technical",
    description:
      "Analysis of attention patterns and context handling in large language models",
    tags: [
      "technical",
      "llm",
      "ai",
      "attention",
      "machine learning",
      "language models",
    ],
    url: "/writing/microblogFiles/llm-quality.html",
    breadcrumb: "Writing > Technical",
  },
  {
    id: "writing-nn",
    title: "The Human Brain as a Neural Network",
    type: "writing",
    category: "Technical",
    description:
      "Exploring parallels between biological and artificial neural networks",
    tags: ["technical", "neural network", "brain", "ai", "neuroscience"],
    url: "/writing/microblogFiles/nn.html",
    breadcrumb: "Writing > Technical",
  },
  {
    id: "writing-bandit",
    title: "Bandit Wargame Walkthrough",
    type: "writing",
    category: "Technical",
    description:
      "Complete walkthrough of the OverTheWire Bandit cybersecurity challenges",
    tags: [
      "technical",
      "cybersecurity",
      "ctf",
      "linux",
      "security",
      "hacking",
      "overthewire",
    ],
    url: "/writing/microblogFiles/bandit.html",
    breadcrumb: "Writing > Technical",
  },

  // Writing - Business & Economics
  {
    id: "writing-value",
    title: "Value",
    type: "writing",
    category: "Business & Economics",
    description: "Exploring the concept of value in business and economics",
    tags: ["business", "economics", "value", "theory", "philosophy"],
    url: "/writing/microblogFiles/value.html",
    breadcrumb: "Writing > Business & Economics",
  },

  // Writing - Reflections/Abstract
  {
    id: "writing-future",
    title: "The Future We Want and How We Get There",
    type: "writing",
    category: "Reflections",
    description: "Thoughts on creating a better future",
    tags: ["philosophy", "future", "society", "reflection", "abstract"],
    url: "/writing/microblogFiles/future1.html",
    breadcrumb: "Writing > Reflections",
  },
  {
    id: "writing-tech-neutral",
    title: "Is Technology Neutral?",
    type: "writing",
    category: "Reflections",
    description:
      "Examining the neutrality of technology and its societal impact",
    tags: ["philosophy", "technology", "society", "ethics", "reflection"],
    url: "/writing/microblogFiles/tech.html",
    breadcrumb: "Writing > Reflections",
  },
  {
    id: "writing-cause",
    title: "Cause and Effect",
    type: "writing",
    category: "Reflections",
    description: "Exploring causality and its implications",
    tags: ["philosophy", "causality", "reflection", "abstract", "thinking"],
    url: "/writing/microblogFiles/cause.html",
    breadcrumb: "Writing > Reflections",
  },
  {
    id: "writing-20",
    title: "20",
    type: "writing",
    category: "Reflections",
    description: "Reflections on turning 20 years old",
    tags: ["reflection", "personal", "life", "age", "growth"],
    url: "/writing/microblogFiles/20.html",
    breadcrumb: "Writing > Reflections",
  },

  // Writing - Archive
  {
    id: "writing-state",
    title: "Turn to State Capitalism",
    type: "writing",
    category: "Archive",
    description: "Analysis of state capitalism trends",
    tags: ["economics", "capitalism", "state", "politics", "archive"],
    url: "/writing/microblogFiles/state.html",
    breadcrumb: "Writing > Archive",
  },
  {
    id: "writing-gap",
    title: "Is This Just How It Works?",
    type: "writing",
    category: "Archive",
    description: "Questioning systemic patterns and norms",
    tags: ["philosophy", "society", "systems", "reflection", "archive"],
    url: "/writing/microblogFiles/gap.html",
    breadcrumb: "Writing > Archive",
  },
  {
    id: "writing-llm-scratch",
    title: "Language Model from Scratch",
    type: "writing",
    category: "Archive",
    description: "Building a language model from first principles",
    tags: ["technical", "llm", "ai", "machine learning", "tutorial", "archive"],
    url: "/writing/microblogFiles/llm.html",
    breadcrumb: "Writing > Archive",
  },
  {
    id: "writing-datetime",
    title: "Date/Time? Who Cares",
    type: "writing",
    category: "Archive",
    description: "Technical challenges with date and time handling",
    tags: ["technical", "datetime", "programming", "archive"],
    url: "/writing/microblogFiles/whocares.html",
    breadcrumb: "Writing > Archive",
  },
  {
    id: "writing-brandfirst",
    title: "Brand First",
    type: "writing",
    category: "Archive",
    description: "Thoughts on brand-first business strategies",
    tags: ["business", "branding", "marketing", "strategy", "archive"],
    url: "/writing/microblogFiles/brandfirst.html",
    breadcrumb: "Writing > Archive",
  },
  {
    id: "writing-complexity",
    title: "Complexity",
    type: "writing",
    category: "Archive",
    description: "Exploring complexity in systems and thinking",
    tags: ["philosophy", "complexity", "systems", "reflection", "archive"],
    url: "/writing/microblogFiles/complexity.html",
    breadcrumb: "Writing > Archive",
  },

  // Experience - Work
  {
    id: "exp-autonommi",
    title: "Software Engineer at Autonommi",
    type: "experience",
    category: "Work",
    description:
      "Working with LLMs and RAG systems, contributing across applied AI, full-stack development, CI/CD, security, and deployment",
    tags: [
      "work",
      "software engineer",
      "autonommi",
      "ai",
      "llm",
      "rag",
      "fullstack",
    ],
    url: "/experience/",
    breadcrumb: "Experience > Work",
  },
  {
    id: "exp-wmb",
    title: "Member of Technical Staff Intern at WMB",
    type: "experience",
    category: "Work",
    description:
      "Researched, developed, and deployed internal procedures and AI workflows",
    tags: ["work", "intern", "wmb", "ai", "workflows", "research"],
    url: "/experience/",
    breadcrumb: "Experience > Work",
  },

  // Experience - Education
  {
    id: "exp-sfu",
    title: "BASc/BBA Joint Major at SFU",
    type: "experience",
    category: "Education",
    description:
      "Computer Science and Business Joint Major with concentration in Artificial Intelligence at Simon Fraser University",
    tags: [
      "education",
      "sfu",
      "computer science",
      "business",
      "ai",
      "university",
    ],
    url: "/experience/",
    breadcrumb: "Experience > Education",
  },
  {
    id: "exp-nus",
    title: "Study Abroad at NUS",
    type: "experience",
    category: "Education",
    description:
      "Studying technology, history, and philosophy at National University of Singapore",
    tags: [
      "education",
      "nus",
      "singapore",
      "study abroad",
      "technology",
      "philosophy",
    ],
    url: "/experience/",
    breadcrumb: "Experience > Education",
  },

  // Experience - Volunteer
  {
    id: "exp-osdc",
    title: "Lead Software Engineer at SFU Open Source Development Club",
    type: "experience",
    category: "Volunteer",
    description:
      "Leading a team of developers and designers in building Financial Fast Feed",
    tags: [
      "volunteer",
      "sfu",
      "open source",
      "leadership",
      "software engineer",
    ],
    url: "/experience/",
    breadcrumb: "Experience > Volunteer",
  },
  {
    id: "exp-sfic",
    title: "Senior Equity Research Analyst at SFU Investment Club",
    type: "experience",
    category: "Volunteer",
    description:
      "Conducting equity research, competing in case competitions, stock pitches, and investment challenges",
    tags: ["volunteer", "sfu", "investment", "finance", "equity research"],
    url: "/experience/",
    breadcrumb: "Experience > Volunteer",
  },
  {
    id: "exp-enactus",
    title: "Project Representative at Enactus Capilano",
    type: "experience",
    category: "Volunteer",
    description:
      "Coordinated events with over 100 participants, competed at Regional and National competitions",
    tags: ["volunteer", "enactus", "leadership", "events", "competition"],
    url: "/experience/",
    breadcrumb: "Experience > Volunteer",
  },
  {
    id: "exp-referee",
    title: "Soccer Referee at St. Pius X School",
    type: "experience",
    category: "Volunteer",
    description:
      "Refereeing soccer games and giving back to elementary school community",
    tags: ["volunteer", "soccer", "referee", "community", "sports"],
    url: "/experience/",
    breadcrumb: "Experience > Volunteer",
  },
];

// Export for use in other scripts
if (typeof module !== "undefined" && module.exports) {
  module.exports = SEARCH_INDEX;
}
